#!/bin/sh

set -e

daemon=${1:?}
state="%{F#d15e85}off%{F-}"
cmd="$(systemctl status $daemon | grep -i run 2>/dev/null || echo '')"

[[ "$cmd" ]] && state="%{F#b3bece}on%{F-}"

echo "%{F#008787}${daemon}%{F-} ${state}"
exit 0
