#! /bin/sh

$(dirname $0)/config

while read -r line ; do

    case $line in

        S*)
            sysR="${line#?}"
            ;;
        T*)
            sysL="${line#?}"
            ;;
        W*)
            wm="${line#?}"
            ;;
    esac

    printf "%s\n" "%{l}${sysL}%{c}${wm}%{r}${sysR}"

done
