{ \
+change-x-forwarded-for{block} \
+client-header-tagger{css-requests} \
+client-header-tagger{image-requests} \
+client-header-filter{hide-tor-exit-notation} \
+deanimate-gifs{last} \
+fast-redirects{check-decoded-url} \
+filter{js-annoyances} \
+filter{unsolicited-popups} \
+filter{all-popups} \
+filter{banners-by-link} \
+filter{banners-by-size} \
+filter{webbugs} \
+filter{tiny-textforms} \
+filter{shockwave-flash} \
+filter{quicktime-kioskmode} \
+filter{ie-exploits} \
+filter{no-ping} \
+filter{google} \
+filter{yahoo} \
+filter{msn} \
+hide-accept-language{en-ca} \
+hide-from-header{block} \
+hide-if-modified-since{-30} \
+hide-referrer{forge} \
+hide-user-agent{Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.8.1.4pre) Gecko/20070404 K-Ninja/2.1.3} \
+overwrite-last-modified{randomize} \
+session-cookies-only \
+set-image-blocker{pattern} \
}
/ # Match all URLs
