#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config presel_feedback_color "#232323"

bspc monitor -d i ii iii iv v vi vii

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a vivaldi desktop=^2
bspc rule -a mpv state=floating
bspc rule -a satie state=floating
bspc rule -a zathura state=floating

$HOME/.config/bspwm/panel &
