#! /bin/sh

IMHERE=$(dirname $0)

# cd $IMHERE
source $IMHERE/panel_config 

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &
echo "T" > "$PANEL_FIFO" &
#clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &
conky -c $IMHERE/panel_conky > "$PANEL_FIFO" &

source $IMHERE/panel_colors

cat "$PANEL_FIFO" \
   | $IMHERE/panel_bar \
   | lemonbar -a 32 \
   -g x$PANEL_HEIGHT \
   -f "$PANEL_FONT" \
   -F "$COLOR_DEFAULT_FG" \
   -B "$COLOR_DEFAULT_BG" &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
